### PR TITLE
Add type hints to docstrings module

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Review by timobrembeck — CHANGES_REQUESTED** [review]
@WhyNotHugo Thanks a lot for your contribution! :muscle: 

Could you exclude the `if TYPE_CHECKING:` from the code coverage report as described in https://github.com/nedbat/coveragepy/issues/831? (Just in `pyproject.toml` instead of `.coveragerc`)

**Comment by WhyNotHugo** [comment]
Updated. I've just realised that I've mis-measuring coverage in a bunch of project too, thanks for the pointer.

**Comment by WhyNotHugo** [comment]
Rebased with pre-commit hooks applied.

**Review by timobrembeck — APPROVED** [review]
Great, thanks! :+1:

I had to add the line `pragma: no cover` to the excluded lines as well, but now the coverage report looks good :ok_hand: 

If you want to, you can also add type hints for the rest of the package :grin:

Also, what do you think about including a tool like [Mypy](https://github.com/marketplace/actions/mypy-action) to check the types as part of the GitHub actions workflow?

**Comment by WhyNotHugo** [comment]
Mypy would help make sure that type hints keep making sense. :+1: 

Right now `sphinxcontrib_django/docstrings/attributes.py` is failing due to a quirk in the type system (`tuple[X]` and `tuple[X, X]` are different types):

```
sphinxcontrib_django/docstrings/attributes.py:20: error: Incompatible types in assignment (expression has type "tuple[Any, Any, Any]", variable has type "tuple[Any, Any]")  [assignment]
```

You might need to use:

```py
FIELD_DESCRIPTORS : tuple[Any,...] = (FileDescriptor, related_descriptors.ForwardManyToOneDescriptor)
```

**Pull request merged**
