### PR TITLE
GitHub Actions: Upgrade to codecov v4

### PR DESCRIPTION
**Pull request by cclauss**
### Short description

GitHub Actions: Upgrade to codecov v4

### Proposed changes

- https://github.com/codecov/codecov-action?tab=readme-ov-file#example-workflowyml-with-codecov-action
- 

### Resolved issues

Fixes: #69

### CODE REVIEW

**Review by timobrembeck — COMMENTED** [review]
@cclauss I really appreciate your effort, but if it doesn't work out in a reasonable amount of time, I think it might not be worth it. Maybe it's really a bug in the upstream action which will be resolved in the future. For the moment, v3 should work just fine for us :smiling_face_with_tear:

**Comment by cclauss** [comment]
Snap!

**Review by timobrembeck — COMMENTED** [review]
Awesome, thanks for figuring that out!
Maybe we have to exclude `setup.py` explicitly from the coverage report to not get a decrease in coverage?
In my opinion, this is justified, since the setup itself is usually never covered by the unit tests, right?

**Comment by cclauss** [comment]
`setup.py` usually goes untested and more and more it is just getting removed.
* https://setuptools.pypa.io/en/latest/deprecated/commands.html

**Comment by timobrembeck** [comment]
> `setup.py` usually goes untested and more and more it is just getting removed.
> 
>     * https://setuptools.pypa.io/en/latest/deprecated/commands.html

Right, I'm also fine with removing it. :+1:
It should have no downsides for users installing this package via pip, right?

**Comment by cclauss** [comment]
Let's not lose `setup.py` in this pull request.  I doubt the loss of one-third of 1% is caused by the presence of `setup.py`.  Once this PR is merged then 99.64% will be the coverage's new normal (green).  See section 06 of https://about.codecov.io/resource/what-is-code-coverage on why 100% coverage is not vital.

**Pull request closed without merging**
